from __future__ import annotations

import asyncio
import io
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import qrcode
from PIL import Image
from pypdf import PdfReader, PdfWriter

from .config import Settings
from .media_processor import MediaProcessingError, MediaProcessor
from .models import MediaRef, NormalizedMessage
from .redis_bus import EventBus
from .waha import WahaClient


TOOLS_HELP = """🧰 ThreadBoss Tools

Send files into Message Yourself, then use:
• make pdf — turn recent images into one PDF
• merge pdfs — merge recent PDFs
• compress pdf — compress the most recent PDF
• resize 1024x1024 — resize the most recent image
• ocr — extract text from the most recent image
• transcribe — transcribe the most recent voice note
• qr <text-or-url> — generate a QR code

Recent attachments are remembered for 10 minutes by default.
""".strip()


@dataclass
class ToolResult:
    handled: bool
    text: str | None = None


class ToolEngine:
    def __init__(self, settings: Settings, bus: EventBus, waha: WahaClient, media: MediaProcessor):
        self.settings = settings
        self.bus = bus
        self.waha = waha
        self.media = media

    async def handle(self, message: NormalizedMessage) -> ToolResult:
        body = message.body.strip()
        lower = body.lower()

        if lower in {"/tools", "tools", "threadboss tools"}:
            return ToolResult(True, TOOLS_HELP)

        if lower.startswith("qr "):
            payload = body[3:].strip()
            if not payload:
                return ToolResult(True, "Send `qr <text-or-url>`.")
            png = await asyncio.to_thread(self._make_qr, payload)
            await self.waha.send_file_bytes(
                message.session_id,
                message.chat_id,
                png,
                filename="threadboss-qr.png",
                mimetype="image/png",
                caption="QR generated by ThreadBoss",
            )
            return ToolResult(True)

        if self._matches(lower, "make pdf", "images to pdf", "convert to pdf", "png to pdf", "jpg to pdf"):
            attachments = await self._recent(message, kind="image")
            if not attachments:
                return ToolResult(True, "Send one or more images first, then send `make pdf`.")
            output = await self._images_to_pdf(attachments)
            await self.waha.send_file_bytes(
                message.session_id,
                message.chat_id,
                output,
                filename="threadboss-images.pdf",
                mimetype="application/pdf",
                caption="✅ PDF created",
            )
            return ToolResult(True)

        if self._matches(lower, "merge pdf", "merge pdfs", "combine pdf", "combine pdfs"):
            attachments = await self._recent(message, kind="pdf")
            if len(attachments) < 2:
                return ToolResult(True, "Send at least two PDFs first, then send `merge pdfs`.")
            output = await self._merge_pdfs(attachments)
            await self.waha.send_file_bytes(
                message.session_id,
                message.chat_id,
                output,
                filename="threadboss-merged.pdf",
                mimetype="application/pdf",
                caption="✅ PDFs merged",
            )
            return ToolResult(True)

        if self._matches(lower, "compress pdf", "compress this pdf", "reduce pdf size"):
            attachments = await self._recent(message, kind="pdf")
            if not attachments:
                return ToolResult(True, "Send a PDF first, then send `compress pdf`.")
            output = await self._compress_pdf(attachments[-1])
            await self.waha.send_file_bytes(
                message.session_id,
                message.chat_id,
                output,
                filename="threadboss-compressed.pdf",
                mimetype="application/pdf",
                caption="✅ PDF compressed",
            )
            return ToolResult(True)

        resize = re.search(r"(?:resize\s+)?(\d{2,5})\s*[x×]\s*(\d{2,5})", lower)
        if resize:
            width, height = int(resize.group(1)), int(resize.group(2))
            if width > 10000 or height > 10000:
                return ToolResult(True, "Maximum resize dimension is 10000 px.")
            attachments = await self._recent(message, kind="image")
            if not attachments:
                return ToolResult(True, "Send an image first, then send e.g. `resize 1024x1024`.")
            data, mimetype, filename = await self.media.download(attachments[-1])
            out, out_name, out_mime = await asyncio.to_thread(self._resize_image, data, filename, width, height)
            await self.waha.send_file_bytes(
                message.session_id,
                message.chat_id,
                out,
                filename=out_name,
                mimetype=out_mime,
                caption=f"✅ Resized to {width}×{height}",
            )
            return ToolResult(True)

        if lower in {"ocr", "extract text", "read this image"}:
            attachments = await self._recent(message, kind="image")
            if not attachments:
                return ToolResult(True, "Send an image first, then send `ocr`.")
            data, mimetype, filename = await self.media.download(attachments[-1])
            text = await self.media.extract_text(data, mimetype, filename)
            return ToolResult(True, text or "I couldn't find readable text in that image.")

        if lower in {"transcribe", "transcribe audio", "transcribe voice"}:
            attachments = await self._recent(message, kind="audio")
            if not attachments:
                return ToolResult(True, "Send a voice note/audio file first, then send `transcribe`.")
            data, _, filename = await self.media.download(attachments[-1])
            text = await self.media.transcribe(data, filename)
            return ToolResult(True, text or "I couldn't transcribe that audio.")

        return ToolResult(False)

    @staticmethod
    def _matches(value: str, *phrases: str) -> bool:
        return any(phrase in value for phrase in phrases)

    async def _recent(self, message: NormalizedMessage, kind: str) -> list[MediaRef]:
        refs = await self.bus.recent_attachments(message.session_id, message.chat_id)
        if kind == "image":
            return [r for r in refs if (r.mimetype or "").startswith("image/")]
        if kind == "audio":
            return [r for r in refs if (r.mimetype or "").startswith("audio/")]
        if kind == "pdf":
            return [r for r in refs if r.mimetype == "application/pdf" or (r.filename or "").lower().endswith(".pdf")]
        return refs

    def _make_qr(self, payload: str) -> bytes:
        img = qrcode.make(payload)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()

    async def _images_to_pdf(self, refs: Sequence[MediaRef]) -> bytes:
        blobs = [await self.media.download(ref) for ref in refs]
        return await asyncio.to_thread(self._images_to_pdf_sync, blobs)

    @staticmethod
    def _images_to_pdf_sync(blobs: Sequence[tuple[bytes, str, str]]) -> bytes:
        images: list[Image.Image] = []
        try:
            for data, _, _ in blobs:
                img = Image.open(io.BytesIO(data)).convert("RGB")
                images.append(img.copy())
            if not images:
                raise MediaProcessingError("No valid images found")
            output = io.BytesIO()
            first, rest = images[0], images[1:]
            first.save(output, format="PDF", save_all=True, append_images=rest)
            return output.getvalue()
        finally:
            for img in images:
                img.close()

    async def _merge_pdfs(self, refs: Sequence[MediaRef]) -> bytes:
        blobs = [await self.media.download(ref) for ref in refs]
        return await asyncio.to_thread(self._merge_pdfs_sync, [b[0] for b in blobs])

    @staticmethod
    def _merge_pdfs_sync(blobs: Sequence[bytes]) -> bytes:
        writer = PdfWriter()
        for blob in blobs:
            reader = PdfReader(io.BytesIO(blob))
            for page in reader.pages:
                writer.add_page(page)
        output = io.BytesIO()
        writer.write(output)
        writer.close()
        return output.getvalue()

    async def _compress_pdf(self, ref: MediaRef) -> bytes:
        data, _, _ = await self.media.download(ref)
        return await asyncio.to_thread(self._compress_pdf_sync, data)

    @staticmethod
    def _compress_pdf_sync(data: bytes) -> bytes:
        with tempfile.TemporaryDirectory() as tmp:
            src = Path(tmp) / "input.pdf"
            dst = Path(tmp) / "output.pdf"
            src.write_bytes(data)
            cmd = [
                "gs",
                "-sDEVICE=pdfwrite",
                "-dCompatibilityLevel=1.4",
                "-dPDFSETTINGS=/ebook",
                "-dNOPAUSE",
                "-dQUIET",
                "-dBATCH",
                f"-sOutputFile={dst}",
                str(src),
            ]
            try:
                subprocess.run(cmd, check=True, capture_output=True, timeout=120)
            except Exception as exc:
                raise MediaProcessingError(f"PDF compression failed: {exc}") from exc
            return dst.read_bytes()

    @staticmethod
    def _resize_image(data: bytes, filename: str, width: int, height: int) -> tuple[bytes, str, str]:
        image = Image.open(io.BytesIO(data)).convert("RGB")
        image = image.resize((width, height), Image.Resampling.LANCZOS)
        output = io.BytesIO()
        suffix = Path(filename).suffix.lower()
        if suffix in {".jpg", ".jpeg"}:
            fmt, mime, ext = "JPEG", "image/jpeg", ".jpg"
        else:
            fmt, mime, ext = "PNG", "image/png", ".png"
        image.save(output, format=fmt, optimize=True)
        return output.getvalue(), f"threadboss-resized-{width}x{height}{ext}", mime
